vich_uploader:
    db_driver: orm
    
    mappings:
        photo_image:
            uri_prefix: /photo
            upload_destination: '%kernel.project_dir%/public/photo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load : false
            delete_on_update : false
            delete_on_remove : false
