#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_cond:
    path: /condition
    methods: GET
    defaults:
        template: registration/conditions.html.twig
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController:templateAction
